version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    image: backend
    env_file: .env
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    networks:
      - backend
  frontend:
    container_name: frontend
    build: ./frontend
    env_file: .env
    restart: always
    ports:
      - '8081:80'
    volumes:
      - type: bind
        source: ./frontend/source
        target: /app/src
    networks:
      - frontend
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    restart: always
    volumes:
      - superpostgres:/data/postgres
    networks:
      - backend

volumes:
  superpostgres:

networks:
  backend:
  frontend: