version: '3'

services:
  backend:
    constainer_name: 'backend'
    build:
      context: backend
      dockerfiel: Dockerfile'
    image: backend
    env_file: .env
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    networks:
      - backend
  frontend:
    constainer_name: 'frontend'
    build:
      context: frontend
      dockerfiel: Dockerfile
    image: 
    env_file: .env
    restart: always
    ports:
      - '8081:80'
    volumes:
      - type: bind
        source: ./frontend/source
        target: /app/src
    networks:
      - frontend

  postgres:
    constainer_name: 'postgres'
    image: postgres:latest
    env_file: .env
    restart: always
    volumes:
      - superpostgres:/data/postgres
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      -8082:8000
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  superpostgres:

networks:
  backend:
  frontend: